matrix:
  include:
  - os: windows
    before_install:
    - choco install visualstudio2019buildtools ; true #<-- ignore demanded reboot
    - choco install visualstudio2019-workload-vctools
    - choco install python3
    - choco install 7zip
  - os: osx
    osx_image: xcode11
  - os: linux
    before_install:
    - sudo apt-get install -y libasound2-dev libgl-dev xorg-dev ftjam

addons:
  homebrew:
    packages:
    - ftjam

language: cpp

install: skip

script:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then travis_wait cmd.exe /C travis_win.bat ; fi
- if [ "$TRAVIS_OS_NAME" != "windows" ]; then python3 rebuild-libs.py all package ; fi

#DEBUG:
#before_deploy:
#  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then find '/c/Program Files (x86)/Microsoft Visual Studio/2019/' ; fi
#  - cd ${TRAVIS_BUILD_DIR}
#  - ls

deploy:
  provider: releases
  api_key:
    secure: PSNUknZ3v+8dkEtzsa2jHl1do/VA4h8ZwhiSU5Vb0YAmv9AdRJbfAdVVjWwieZAEJrdwdjELELB8B6Zu0hW4ifbpGRZUevSSfyvJs+XmdqD/mO4F9xFfARF6I7b80kqrlIC+3Kybi9pxap0jlArqU4S8qclgq8jEb81WhA1ib5c5jOBgJKWTFul4IIw1QwLMnImdlJlT5QUhRpRf2KW2GTmZmgfHEEX6aTOitsdZOJKHl5bsnIjO0RO0H5ognmYhRO6ty8ko1mEqO307DxdG5Y746xSxOETWRODS6Wcpve9jtxQ8jRg3a0gfIIqsGyTlmC5wpG97PRVwFLiiHEfMuFpd8V9Vcg9mKAVa/1VWooJP9FvQSdnr6+1Vl6Biw0498Kee0/6qUwBVg5+0yBEbYTdc+9HZVCQmKFL+K9FhU0h+QTqnRypi2sbPf/eEb5ETkN9U5jFcp5cgEeVTr0jXVqt4+IL5Z2m3DKKbS7S+Z6WzN6uwDYqteqQkLVtgyZZ/v2ugTFAbWjY3l6cvHMrqmnmQQz0hB877HDhtONGUIN2xHlCvXWDduFUNr4CyXi/jJ3WGG4xbMeravxi43ILEKjjFrQXoi3bHUwRTR+UXM3fswK6A06QQuToEFXf3qzabPMZ9zyPyrFp9xu5jexTYd08ubTlrHCFuaENV3/PULJg=
  file: nest-libs-*-${TRAVIS_TAG}.*
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
    repo: 15-466/nest-libs
