matrix:
  include:
    - os: windows
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -V
        - choco install 7zip
    - os: osx
      osx_image: xcode11
    - os: linux

language: cpp
install: skip

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then python rebuild-libs.py all package ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then python3 rebuild-libs.py all package ; fi
#deploy:
#  skip_cleanup: true
