matrix:
  include:
    - os: windows
  #  - os: osx
  #    osx_image: xcode11
  #  - os: linux

language: cpp
install: skip

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install 7zip ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python3 ; fi

script:
  cmd.exe /C "python.exe rebuild-libs.py all"
  #- if [ "$TRAVIS_OS_NAME" = "windows" ]; then python rebuild-libs.py all ; fi
  #- if [ "$TRAVIS_OS_NAME" != "windows" ]; then python3 rebuild-libs.py all ; fi
#deploy:
#  skip_cleanup: true
