@echo Calling vcvars64.bat...
call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
@echo Running python...
C:\Python37\python rebuild-libs.py all package
@echo Done.
