name: Build Libraries
on:
  push:
  release:
    types: [created]


jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Code
        shell: cmd
        run: |
          dir/w
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          python rebuild-libs.py all package
