name: Build Libraries
on:
  release:
    types: [created]


jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Code
        shell: cmd
        run: |
          dir/w
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          python rebuild-libs.py all package
      - name: Upload Result
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TAG_NAME: ${{ github.event.tag_name }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: nest-libs-windows-${{ github.event.tag_name }}.zip
          asset_name: nest-libs-windows-${{ github.event.tag_name }}.zip
          asset_content_type: application/zip
