name: Build Libraries
on:
  push:
  release:
    types: [created]


jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, 'runWindows')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Code
        shell: cmd
        #maybe this from will work: https://github.com/cisco/ChezScheme/blob/main/c/vs.bat
        run: |
          dir/w
          echo ProgramW6432: %ProgramW6432%
          echo %ProgramW6432%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat "amd64"
          dir "%ProgramW6432%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\"
          call "%ProgramW6432%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          python rebuild-libs.py all package
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - name: Upload Result
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: nest-libs-windows-${{ github.event.release.tag_name }}.zip
          asset_name: nest-libs-windows-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
      - name: Upload Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: nest-libs-windows
          path: nest-libs-*.zip

  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'runLinux')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Code
        shell: bash
        run: |
          sudo apt update
          sudo apt install ftjam libgl-dev libasound2-dev libpulse-dev #some of these probably needed for fullscreen: libxinerama-dev libxinput2-dev libxrandr-dev libxscrnsaver-dev libxvidmode-dev
          pip3 install --user meson
          python3 rebuild-libs.py all package
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - name: Upload Result
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: nest-libs-linux-${{ github.event.release.tag_name }}.tar.gz
          asset_name: nest-libs-linux-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip
      - name: Upload Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: nest-libs-linux
          path: nest-libs-*.tar.gz

  build-macos:
    name: Build (MacOS)
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, 'runMac')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Code
        shell: bash
        run: |
          brew install ftjam meson
          python3 rebuild-libs.py all package
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - name: Upload Result
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: nest-libs-macos-${{ github.event.release.tag_name }}.tar.gz
          asset_name: nest-libs-macos-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip
      - name: Upload Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: nest-libs-osx
          path: nest-libs-*.tar.gz
